name: Build MLinux Minimal

on:
  push:
  workflow_dispatch:

jobs:
  build-binary:
    
    runs-on: ubuntu-latest
    container: debian:bullseye
    
    steps:
    
    #--------------------------------------------collect--------------------------------------------
    - name: Get infomations
      uses: actions/checkout@v4
    - name: Collect dependencies
      run: |
        apt-get update && sudo apt-get install gcc cpio xz-utils gawk make grep qemu-utils sed util-linux wget binutils libelf-dev libssl-dev bc flex bison rsync -y
        apt-get install gcc cpio xz-utils gawk syslinux make grep qemu-utils sed util-linux ccache icecc distcc wget binutils libelf-dev libssl-dev bc flex bison rsync cmake ninja-build -y
    #--------------------------------------------build--------------------------------------------
    
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true
        key: max-size
        max-size: 996M
    - name: configure
      run: |
        cmake . -GNinja
    - name: Build
      run: |
        ninja -v
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: disk.img
