name: Build MLinux Minimal

on:
  push:

jobs:
  build-binary:
  
    needs: build-dist
    
    runs-on: ubuntu-latest
    
    steps:
    
    #--------------------------------------------collect--------------------------------------------
    - name: Get infomations
      run: actions/checkout@v4
    - name: Collect dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc cpio xz-utils gawk syslinux make grep qemu-utils sed util-linux wget -y
        sudo apt-get install binutils libelf-dev libssl-dev bc flex bison rsync -y
    #--------------------------------------------build--------------------------------------------
    
    - name: Build binary distribution
      run: |
        ./configure
        make all -j$(nproc)
    
    - name: Make packages
      run: |
        sha256sum disk.img.xz > disk.img.xz.sha256
        sha256sum rootfs.tar.xz > rootfs.tar.xz.sha256
        sha256sum vmlinuz.xz > vmlinuz.xz.sha256
    
    #--------------------------------------------publish--------------------------------------------

