name: Build MLinux Minimal

on:
  push:

jobs:
  build-binary:
    
    runs-on: ubuntu-latest
    
    steps:
    
    #--------------------------------------------collect--------------------------------------------
    - name: Get infomations
      uses: actions/checkout@v4
    - name: Collect dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc cpio xz-utils gawk syslinux make grep qemu-utils sed util-linux wget -y
        sudo apt-get install binutils libelf-dev libssl-dev bc flex bison rsync -y
    #--------------------------------------------build--------------------------------------------
    
    - name: Autogen
      run: |
        aclocal
        autoheader -v
        libtoolize --automake --copy --force
        autoconf -v
        automake --add-missing --force-missing --copy --foreign 
        
    - name: configure
      run: |
        ./configure
    - name: Build
      run: |
        make all -j$(nproc)
