name: Build MLinux Minimal

on:
  push:

jobs:

  build-dist:

    runs-on: ubuntu-latest

    steps:

    #--------------------------------------------collect--------------------------------------------
    - uses: actions/checkout@v4
    
    - name: Get infomations
      run: |
        tag="${GITHUB_REF#refs/tags/}"
        echo "tag=$tag" >> $GITHUB_ENV
        echo "pkgname=mlinux-minimal-$tag" >> $GITHUB_ENV
        echo "srcdir=$(pwd)" >> $GITHUB_ENV

    - name: Collect dependencies
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake -y

    #--------------------------------------------build--------------------------------------------
    - name: Build tarball
      run: |
        sudo make -f Makefile.devel dist VERSION=${{ env.tag }}
    
    - name: Sum md5
      run: |
        sudo sha256sum ${{ env.pkgname }}.tar.xz > ${{ env.pkgname }}.tar.xz.sha256
    
    #--------------------------------------------publish--------------------------------------------

  build-binary:
  
    needs: build-dist
    
    runs-on: ubuntu-latest
    
    steps:
    
    #--------------------------------------------collect--------------------------------------------
    - name: Get infomations
      run: |
        tag="${GITHUB_REF#refs/tags/}"
        echo "tag=$tag" >> $GITHUB_ENV
        echo "pkgname=mlinux-minimal-$tag" >> $GITHUB_ENV
        echo "srcdir=$(pwd)" >> $GITHUB_ENV

    - name: Collect dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc cpio xz-utils gawk syslinux make grep qemu-utils sed util-linux wget -y
        sudo apt-get install binutils libelf-dev libssl-dev bc flex bison rsync -y

    - name: Get source distribution tarball
      run: |
        wget https://github.com/${{ github.repository }}/releases/download/${{ env.tag }}/${{ env.pkgname }}.tar.xz
        tar xvf ${{ env.pkgname }}.tar.xz
        mv ${{ env.pkgname }}/* .
    
    #--------------------------------------------build--------------------------------------------
    
    - name: Build binary distribution
      run: |
        ./configure
        make all -j$(nproc)
    
    - name: Make packages
      run: |
        sha256sum disk.img.xz > disk.img.xz.sha256
        sha256sum rootfs.tar.xz > rootfs.tar.xz.sha256
        sha256sum vmlinuz.xz > vmlinuz.xz.sha256
    
    #--------------------------------------------publish--------------------------------------------

